"""dot

Revision ID: 2d549d8aaf49
Revises: a867ec854a94
Create Date: 2018-04-21 21:39:41.255367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d549d8aaf49'
down_revision = 'a867ec854a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comment', sa.Column('reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'reply', ['reply_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'reply_id')
    op.drop_table('reply')
    # ### end Alembic commands ###
