"""Initial Migration

Revision ID: a867ec854a94
Revises: 1dc14e63e256
Create Date: 2018-04-21 21:02:43.409840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a867ec854a94'
down_revision = '1dc14e63e256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'comment_id')
    op.drop_table('comment')
    # ### end Alembic commands ###
