"""dot

Revision ID: cd1aa98b21f5
Revises: ee2a1ade1fc1
Create Date: 2018-04-23 00:30:30.880793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1aa98b21f5'
down_revision = 'ee2a1ade1fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_post_id_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'post_id')
    op.add_column('post', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'comment_id')
    op.add_column('comment', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_post_id_fkey', 'comment', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
