"""dot

Revision ID: dea7f6d0dcf7
Revises: 2d549d8aaf49
Create Date: 2018-04-21 21:44:22.752381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea7f6d0dcf7'
down_revision = '2d549d8aaf49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('reply', sa.Text(), nullable=True))
    op.drop_column('reply', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('reply', 'reply')
    # ### end Alembic commands ###
