"""dot

Revision ID: ee2a1ade1fc1
Revises: dea7f6d0dcf7
Create Date: 2018-04-23 00:11:04.587169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2a1ade1fc1'
down_revision = 'dea7f6d0dcf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_constraint('post_comment_id_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_comment_id_fkey', 'post', 'comment', ['comment_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###
